### ISSUE TITLE
Errors while installing Scico manually

### ISSUE THREAD

**Issue by FernandoDavis** [lanl/scico#11]
When I tried to install scico I ran into the following message using the command `pip install -e .`

ERROR: Package 'scico' requires a different Python: 3.6.9 not in '>3.8'

If I changed the version in setup.py to >= 3.6.9 it finished doing the installation, otherwise, there was no progress.

Additionally, running `pip install -r requirements.txt` threw an error about not recognizing JAX above or equal to 0.2.19. And halted install progress there too. I updated my pip and pip3 and ran them but no progress. Not sure if it was a mistake on my end.

**Comment by lukepfister** [comment]
Your python version currently 3.6.9, and scico requires something greater than 3.8.

This is for a good reason (type annotations).  If you are using conda, you can create an environment with python 3.8 using:

`conda create -n scico python=3.8`.

**Comment by FernandoDavis** [comment]
That's odd since I tried it with 3.8.11 but I'll check the conda installation. Thank you!

**Comment by lukepfister** [comment]
This line: `Python: 3.6.9 not in '>3.8'` means that the python version is 3.6.9.  

You can check the python version using `python --version`.

Note that if you're using a conda environment, you may need to explicitly install pip (`conda install pip`).  Otherwise pip might be the **system** python pip, which is not what you want!  You can check that using `which pip` and seeing if it points to something like `/usr/bin/python/bin/pip` (system python) or something like `/home/pfister/miniconda/bin/pip` (the conda pip).

**Comment by FernandoDavis** [comment]
Ah that's fair! I think I can manage with this info so i'll close this. Thanks again!
