### ISSUE TITLE
Not compatible with jaxlib/jax 0.3.15

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#317]
Tests are failing and there are new deprecation warnings to be addressed when using jaxlib/jax 0.3.15.

**Comment by Michael-T-McCann** [comment]
As far as I can tell, fixing this will require refactoring `BlockArray` to not derive from `list`.

The important situation is `a * x` where `a` is a (scalar)`DeviceArray` and `x` is a `BlockArray`. In the old days, this would get dispatched to `DeviceArray`, it would return `NotImplemented` and then it would get dispatched to `BlockArray` which would handle it correctly. In jax 0.3.15, there is

```
_rejected_binop_types = (list, tuple, set, dict)
if isinstance(other, _rejected_binop_types):
  raise TypeError(...)
```
Because `BlockArray` derives from `list`, we get an error.

The relevant jax change is "Binary operations between JAX arrays and built-in collections (dict, list, set, tuple) now raise a TypeError in all cases. Previously some cases (particularly equality and inequality) would return boolean scalars inconsistent with similar operations in NumPy ([#11234](https://github.com/google/jax/issues/11234))." (https://jax.readthedocs.io/en/latest/changelog.html).
