### ISSUE TITLE
 flax requirements updates?

### ISSUE THREAD

**Issue by ocehugo** [lanl/scico#571]
Hi devs,

If one follows the latest jax/flax, scico can't be installed since it is locked to flax<0.9.

My limited tests indicated that flax could be up to at least < =0.10.2 without triggering any changes in the testing suite. I'm finding the same testing results when bumping the version when using master:

```
4692 passed, 23 skipped, 27 xfailed, 2 warnings
```

Is this expected? The bumped version works for my workflow and helps me avoid cloning the env/downgrade just for scico dependency.

**Comment by bwohlberg** [comment]
Thanks for reporting the `flax` version issue. Since new releases of `jax` and `flax` often break some component of `scico`, we have been placing upper bounds on the versions of these packages so that `scico` releases aren't broken by new releases of these packages. The intent is to keep these bounds current for the development version of `scico` though, so we can certainly bump the `flax` bound to 0.10.2 as recommended.
