### ISSUE TITLE
Support running tests in parallel

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#92]
Since our test suite takes quite a while to run, it would be convenient to be able to run the tests in parallel using either [pytest-xdist](https://github.com/pytest-dev/pytest-xdist) or [pytest-parallel](https://github.com/browsertron/pytest-parallel). Unfortunately neither of these pytest plugins works at the moment

- pytest-xdist fails in the test collection phase (possibly related to pytest-dev/pytest-xdist#432)
- pytest-parallel hangs in the test execution phase

**Comment by FernandoDavis** [comment]
The following are the only tests that do not work with x-dist:

- scico/test/test_admm.py
Fails due to mismatch of results. Not sure if directly related to x-dist or if it's a mistake in my current build.
- scico/test/test_functional.py
Different tests were collected between workers. This is likely due to concurrency issues in data between test classes/methods.

After I finish taking care of other issues I will proceed and fix these two modules so that they are compatible. Could be a big or small change though, will update this thread on findings.

**Comment by bwohlberg** [comment]
Closing for now since this is largely addressed in #390.
